# Generated by Django 4.1.1 on 2022-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnModels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.AddField(
            model_name='post',
            name='post_rating',
            field=models.IntegerField(default=0),
        ),
    ]
