# Generated by Django 4.1.1 on 2022-10-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnModels', '0002_remove_post_rating_post_post_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='id_user',
        ),
    ]
