# Generated by Django 4.1.1 on 2022-10-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnModels', '0003_rename_user_author_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('news', 'Новости'), ('article', 'Статья')], default='news', max_length=10),
        ),
    ]
