# Generated by Django 4.1.1 on 2022-11-05 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnModels', '0005_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscriber',
            field=models.ManyToManyField(through='LearnModels.Subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
